# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b9d762ce99d8ded86f72a60f3589ece040c753e34e20bcaff02a11d878ec0eff48ac2570b225f4ceb14e68b18bb80ef69e22f9f783b141aa3792950971543e1

test:
  secret_key_base: cdf0789fc322dc73edb0b3d112d7d7718033d82d647855ac0ed6d1dfda3b65d717a3db59e49b14baf232d73992ba424d3626364ada490b49fa1dce44fc598912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
